# Generated by Django 6.1.1 on 2026-09-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadsavedfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='activity_type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='call_result',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_unit_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_follow_up',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_modified_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='legacy_created_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='legacy_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='legacy_modified_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='salutation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
