# Generated by Django 6.1.1 on 2026-09-12 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_notes', to='properties.property')),
            ],
            options={
                'db_table': 'properties_property_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offer_date', models.DateField(default=django.utils.timezone.now)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Counter Offer'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_offers', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.property')),
            ],
            options={
                'db_table': 'properties_property_offer',
                'ordering': ['-offer_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyViewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_name', models.CharField(max_length=200)),
                ('prospect_phone', models.CharField(blank=True, max_length=20)),
                ('prospect_email', models.EmailField(blank=True, max_length=254)),
                ('viewing_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_viewings', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='properties.property')),
            ],
            options={
                'db_table': 'properties_property_viewing',
                'ordering': ['-viewing_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('square_feet', models.PositiveIntegerField()),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tenant_name', models.CharField(blank=True, max_length=200)),
                ('tenant_phone', models.CharField(blank=True, max_length=20)),
                ('lease_start', models.DateField(blank=True, null=True)),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'db_table': 'properties_property_unit',
                'ordering': ['unit_number'],
                'unique_together': {('related_property', 'unit_number')},
            },
        ),
    ]
