# Generated by Django 6.1.1 on 2026-09-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertynote_propertyoffer_propertyviewing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='area_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='building',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='business_activity',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='call_made_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='call_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='call_update',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='community_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='compound_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='compound_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='duplicate_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='finishing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='handler',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='land_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='last_call_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='last_follow_in',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='last_modified_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='legacy_created_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='legacy_modified_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_purpose',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='mall_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='more_units',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='phase',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='property_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='property_offered_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='reminder_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='reminder_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='sales',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='send_a_message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='space_m',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_license',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='update_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='property',
            name='view_me',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
