# Generated by Django 6.1.1 on 2026-09-11 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#ffc107', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('probability', models.PositiveIntegerField(default=0, help_text='Probability of closing (%)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'opportunities_opportunity_stage',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('opportunity_type', models.CharField(choices=[('sale', 'Sale'), ('rental', 'Rental'), ('lease', 'Lease')], max_length=20)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_close_date', models.DateField()),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('probability', models.PositiveIntegerField(default=0, help_text='Probability of closing (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='leads.lead')),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='properties.property')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opportunities.opportunitystage')),
            ],
            options={
                'db_table': 'opportunities_opportunity',
                'ordering': ['-created_at'],
            },
        ),
    ]
